apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-mcm-pl
spec:
  params:
  - description: The event type
    name: event-type
    type: string
  - description: The event ref
    name: event-ref
    type: string
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: test
    resources:
      inputs:
      - name: source
        resource: git-source
    taskRef:
      kind: Task
      name: igc-nodejs-test
  - name: build-push-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
      - name: git-source
        resource: git-source
    runAfter:
    - test
    taskRef:
      kind: Task
      name: nodejs-build-push-task
  - name: image-scan-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
    runAfter:
    - build-push-task
    taskRef:
      kind: Task
      name: nodejs-image-scan-task
  - name: gitops
    resources:
      inputs:
      - name: source
        resource: git-source
      - name: image
        resource: docker-image
    runAfter:
    - image-scan-task
    taskRef:
      kind: Task
      name: gitops
  - name: slack-post-dev
    params:
    - name: message
      value: '> storefront-ui in proj-a-dev has been updated with image $(inputs.resources.image.url).'
    - name: webhook-secret
      value: slack-webhook-secret
    resources:
      inputs:
      - name: image
        resource: docker-image
    runAfter:
    - gitops
    taskRef:
      kind: Task
      name: send-to-webhook-slack
  - name: automation-testing
    resources:
      inputs:
      - name: source
        resource: git-source
      - name: image
        resource: docker-image
    runAfter:
    - slack-post-dev
    taskRef:
      kind: Task
      name: automation-testing
  - name: gitops-pr
    resources:
      inputs:
      - name: source
        resource: git-source
      - name: image
        resource: docker-image
    runAfter:
    - automation-testing
    taskRef:
      kind: Task
      name: gitops-pr
  # - name: slack-post-qa
  #   params:
  #   - name: message
  #     value: '> storefront-ui in proj-a-qa has a pull reqeust to promote $(inputs.resources.image.url).'
  #   - name: webhook-secret
  #     value: slack-webhook-secret
  #   resources:
  #     inputs:
  #     - name: image
  #       resource: docker-image
  #   runAfter:
  #   - gitops-pr
  #   taskRef:
  #     kind: Task
  #     name: send-to-webhook-slack
